stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    - src/utils.py
    - params.yaml
    outs:
    - data/raw/train.csv
    - data/raw/test.csv
  pre_processing:
    cmd: python src/data_prep.py
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - src/data_prep.py
    - src/utils.py
    outs:
    - data/processed/train_processed.csv
    - data/processed/test_processed.csv
  model_selection:
    cmd: python src/exp1.py
    deps:
    - data/processed/train_processed.csv
    - data/processed/test_processed.csv
    - src/exp1.py
    - src/utils.py
    - params.yaml
    outs:
    - best_model.txt
  hyperparameter_tuning:
    cmd: python src/exp2.py
    deps:
    - data/processed/train_processed.csv
    - best_model.txt
    - src/exp2.py
    - src/utils.py
    - params.yaml
    outs:
    - best_model_params.json
  model_eval:
    cmd: python src/model_eval.py
    deps:
    - data/processed/train_processed.csv
    - data/processed/test_processed.csv
    - best_model.txt
    - best_model_params.json
    - src/utils.py
    - src/model_eval.py
    metrics:
    - metrics.json
    outs:
    - feature_importances.png
    - confusion_matrix.png
    - model_eval.txt
